name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Who Am I?
        run: npm whoami --registry https://registry.npmjs.org
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
